"""create festival

Revision ID: f794398dd510
Revises: f45bf61af117
Create Date: 2025-08-14 20:07:23.534193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f794398dd510'
down_revision: Union[str, Sequence[str], None] = 'f45bf61af117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festival',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('period_raw', sa.String(length=120), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('image_src', sa.Text(), nullable=True),
    sa.Column('image_alt', sa.String(length=300), nullable=True),
    sa.Column('detail_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash', name='uq_festival_hash')
    )
    op.create_index('ix_festival_created_at', 'festival', ['created_at'], unique=False)
    op.create_index('ix_festival_period_start', 'festival', ['period_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_festival_period_start', table_name='festival')
    op.drop_index('ix_festival_created_at', table_name='festival')
    op.drop_table('festival')
    # ### end Alembic commands ###
